// Package firewall renders and applies Drawbridge's nftables table (ADR 0006).
//
// Drawbridge owns only `table inet drawbridge`. It holds NAT and restrictive rules, never
// accepts, because an accept in one table can't override a drop in another
// (docs/PLAN.md §5.3). The whole table is replaced in one `nft -f` transaction.
package firewall

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/netip"
	"os"
	"os/exec"
	"strings"
	"sync"
)

// Table is the nftables table Drawbridge owns.
const Table = "inet drawbridge"

// commentPrefix starts the table's comment, which records the ruleset's revision so the
// drift check can tell whether the table in the kernel is the one Drawbridge rendered.
const commentPrefix = "drawbridge rev "

// Rules are the inputs to the ruleset. Every field is a validated value (model.Settings
// validates the interface name and prefixes), so nothing here needs quoting.
type Rules struct {
	Interface string
	// IPv4 and IPv6 are the VPN subnets to masquerade. A zero IPv6 prefix means no
	// IPv6 NAT.
	IPv4, IPv6      netip.Prefix
	ClientIsolation bool
	// AdminPort, when set, is the web UI's TCP port. Only sources in AdminAllowed can
	// reach it (docs/PLAN.md §6.5), whatever the host firewall or the router allows.
	AdminPort uint16
	// AdminAllowed must be normalized (lan.Allowlist): nftables interval sets reject
	// overlapping elements.
	AdminAllowed []netip.Prefix
}

// Ruleset is a rendered table and its revision.
type Ruleset struct {
	Text     string
	Revision string
}

// Render renders the table.
func Render(r Rules) Ruleset {
	var body strings.Builder
	iface := r.Interface

	if r.AdminPort != 0 {
		var v4, v6 []string
		for _, p := range r.AdminAllowed {
			if p.Addr().Is4() {
				v4 = append(v4, p.String())
			} else {
				v6 = append(v6, p.String())
			}
		}
		writeSet(&body, "admin_allowed4", "ipv4_addr", v4)
		writeSet(&body, "admin_allowed6", "ipv6_addr", v6)
		// The admin UI is never reachable from the internet, even if the router lets
		// inbound IPv6 through to the host. The host's own traffic is exempt.
		body.WriteString("\tchain input {\n")
		body.WriteString("\t\ttype filter hook input priority filter; policy accept;\n")
		body.WriteString("\t\tiif \"lo\" accept\n")
		fmt.Fprintf(&body, "\t\ttcp dport %d ip saddr != @admin_allowed4 drop\n", r.AdminPort)
		fmt.Fprintf(&body, "\t\ttcp dport %d ip6 saddr != @admin_allowed6 drop\n", r.AdminPort)
		body.WriteString("\t}\n")
	}

	body.WriteString("\tchain forward {\n")
	body.WriteString("\t\ttype filter hook forward priority filter; policy accept;\n")
	if r.ClientIsolation {
		fmt.Fprintf(&body, "\t\tiifname %q oifname %q drop\n", iface, iface)
	}
	body.WriteString("\t}\n")

	// Clamp TCP's maximum segment size to the route's MTU in both directions, for paths
	// where MTU discovery is broken (docs/PLAN.md §5.4).
	body.WriteString("\tchain mss_clamp {\n")
	body.WriteString("\t\ttype filter hook forward priority mangle; policy accept;\n")
	fmt.Fprintf(&body, "\t\toifname %q tcp flags syn tcp option maxseg size set rt mtu\n", iface)
	fmt.Fprintf(&body, "\t\tiifname %q tcp flags syn tcp option maxseg size set rt mtu\n", iface)
	body.WriteString("\t}\n")

	// Masquerade the VPN subnets on every interface except the tunnel itself: the
	// internet uplink, and the LAN, whose devices have no route back to the VPN.
	body.WriteString("\tchain postrouting {\n")
	body.WriteString("\t\ttype nat hook postrouting priority srcnat; policy accept;\n")
	fmt.Fprintf(&body, "\t\tip saddr %s oifname != %q masquerade\n", r.IPv4.Masked(), iface)
	if r.IPv6.IsValid() {
		fmt.Fprintf(&body, "\t\tip6 saddr %s oifname != %q masquerade\n", r.IPv6.Masked(), iface)
	}
	body.WriteString("\t}\n")

	sum := sha256.Sum256([]byte(body.String()))
	rev := hex.EncodeToString(sum[:6])
	var out strings.Builder
	out.WriteString("# Generated by Drawbridge. Do not edit; changes are overwritten.\n")
	fmt.Fprintf(&out, "table %s {\n", Table)
	fmt.Fprintf(&out, "\tcomment %q\n", commentPrefix+rev)
	out.WriteString(body.String())
	out.WriteString("}\n")
	return Ruleset{Text: out.String(), Revision: rev}
}

// writeSet writes an interval set of prefixes. An empty set is valid, and matches
// nothing.
func writeSet(b *strings.Builder, name, typ string, elements []string) {
	fmt.Fprintf(b, "\tset %s {\n", name)
	fmt.Fprintf(b, "\t\ttype %s\n", typ)
	b.WriteString("\t\tflags interval\n")
	if len(elements) > 0 {
		fmt.Fprintf(b, "\t\telements = { %s }\n", strings.Join(elements, ", "))
	}
	b.WriteString("\t}\n")
}

// Runner runs nft with the given arguments and standard input, and returns its combined
// output. Tests and the integration suite replace it.
type Runner func(ctx context.Context, stdin string, args ...string) ([]byte, error)

// Nft runs the nft binary. The daemon's ambient CAP_NET_ADMIN passes to it. It's the
// only external command Drawbridge runs, always with an argument list and never through
// a shell (ADR 0007).
func Nft(ctx context.Context, stdin string, args ...string) ([]byte, error) {
	path, err := exec.LookPath("nft")
	if err != nil {
		path = "/usr/sbin/nft"
	}
	// path is nft from PATH (or its standard location), and args are Drawbridge's own
	// constants, never user input.
	cmd := exec.CommandContext(ctx, path, args...) //nolint:gosec // G204, see above.
	cmd.Stdin = strings.NewReader(stdin)
	out, err := cmd.CombinedOutput()
	if errors.Is(err, exec.ErrNotFound) {
		return out, errors.New("nft isn't installed; Drawbridge needs the nftables package")
	}
	return out, err
}

// Applier applies and inspects Drawbridge's table.
type Applier struct {
	Run Runner
	// SavePath, when set, receives a copy of each ruleset Apply loads, so the admin can
	// read what's in the kernel (docs/PLAN.md §4.4).
	SavePath string
}

// NewApplier returns an Applier that runs the nft binary and saves each applied ruleset
// at savePath ("" to not save it).
func NewApplier(savePath string) *Applier {
	return &Applier{Run: Nft, SavePath: savePath}
}

// replacePrefix makes the transaction replace the table: create it if it's missing,
// delete it, then define it. nft applies the whole file atomically.
const replacePrefix = "table " + Table + "\ndelete table " + Table + "\n"

// Apply replaces the table with the ruleset in one transaction.
func (a *Applier) Apply(ctx context.Context, rs Ruleset) error {
	if out, err := a.Run(ctx, replacePrefix+rs.Text, "-f", "-"); err != nil {
		return fmt.Errorf("applying the nftables ruleset: %w: %s", err, bytes.TrimSpace(out))
	}
	if a.SavePath != "" {
		if err := os.WriteFile(a.SavePath, []byte(rs.Text), 0o600); err != nil {
			return fmt.Errorf("the ruleset is applied, but saving a copy failed: %w", err)
		}
	}
	return nil
}

// Remove deletes the table. A missing table isn't an error.
func (a *Applier) Remove(ctx context.Context) error {
	if out, err := a.Run(ctx, replacePrefix, "-f", "-"); err != nil {
		return fmt.Errorf("removing the nftables table: %w: %s", err, bytes.TrimSpace(out))
	}
	return nil
}

// Revision returns the revision of the table in the kernel, and false if the table
// doesn't exist.
func (a *Applier) Revision(ctx context.Context) (string, bool, error) {
	out, err := a.Run(ctx, "", "-j", "list", "table", "inet", "drawbridge")
	if err != nil {
		if bytes.Contains(out, []byte("No such file or directory")) {
			return "", false, nil
		}
		return "", false, fmt.Errorf("listing the nftables table: %w: %s", err, bytes.TrimSpace(out))
	}
	var listing struct {
		Nftables []struct {
			Table *struct {
				Comment string `json:"comment"`
			} `json:"table"`
		} `json:"nftables"`
	}
	if err := json.Unmarshal(out, &listing); err != nil {
		return "", false, fmt.Errorf("parsing nft's JSON output: %w", err)
	}
	for _, item := range listing.Nftables {
		if item.Table != nil {
			return strings.TrimPrefix(item.Table.Comment, commentPrefix), true, nil
		}
	}
	return "", false, nil
}

// Memory holds the ruleset in memory instead of the kernel. `drawbridge serve --backend
// fake` uses it, so the web UI can be developed without root.
type Memory struct {
	mu  sync.Mutex
	rev string
}

// Apply records the ruleset's revision.
func (m *Memory) Apply(_ context.Context, rs Ruleset) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.rev = rs.Revision
	return nil
}

// Remove forgets the ruleset.
func (m *Memory) Remove(context.Context) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.rev = ""
	return nil
}

// Revision returns the recorded revision.
func (m *Memory) Revision(context.Context) (string, bool, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.rev, m.rev != "", nil
}
